CMakeLists.txt

New C++11 standard is started to be used by default on some distros (e.g. arch). In order to avoid any problems with building on these distros, C++ standard flag should be set explicitly to ~~c++98~~ c++03.

set explicitly the C++ standard to use

---

shippable.yml

- The CI service I used is *shippable*
- The build is done inside the official Ubuntu Docker containers for *Trusty* and *Xenial*
- The build scripts compiles *vartypes* as a source dependency
Project URL: https://app.shippable.com/projects/5620224e1895ca44741e0b4d/status/

[CI] Add the initial shippable config file for building grSim

---

config/Parsian.ini
config/ParsianNew.ini
config/RoboIME2012.ini

Friction is spelled correctly in the code base, but not in the config files meaning only defaults were being used.

Fix spelling: fiction -> friction

---

src/sslworld.cpp

A typo in the definition of the geometry line causes one of the line to be off.

Fix LeftPenaltyStretch line in geometry package

---

include/mainwindow.h
src/main.cpp
src/mainwindow.cpp

A grSim headless mode would be very nice to have, especially when considering that grSim takes up significant CPU resources on displaying a 3d world.
This headless mode tries to improve performance (and convenience) by hiding the qt window and turning off the openGL window when passed the `-headless` flag.
Please let me know if you think anything could be improved!

Add a grSim headless mode

---

include/config.h
include/configwidget.h
include/mainwindow.h
include/physics/pworld.h
include/robotwidget.h
include/sslworld.h
src/configwidget.cpp
src/glwidget.cpp
src/mainwindow.cpp
src/physics/pworld.cpp
src/robotwidget.cpp
src/sslworld.cpp

Implement changes for #66 which itself is a follow up on #59 .
- Add field parameter for division A and B. Also, add a parameter to easily switch between the two.
- Add a robots count parameter, which update the number of robot on the field.
The default parameter values should follow the [2018 official rules](http://wiki.robocup.org/images/7/73/Small_Size_League_-_Rules_2018.pdf).

Feature switch between division

---

clients/qt/CMakeLists.txt

Fixes below issue in newer versions of cmake package that doesn't allow mixing  of qt3/qt4.
`CMake Error at /usr/share/cmake-3.11/Modules/FindQt3.cmake:44 (message):
Qt3 and Qt4 cannot be used together in one project.
Call Stack (most recent call first):
/usr/share/cmake-3.11/Modules/FindQt.cmake:151 (include)
clients/qt/CMakeLists.txt:10 (find_package)
`

Specify qt4 for client

---

src/sslworld.cpp

#91 
Go from this:
To this:
Qt supplies a `devicePixelRatio` value to convert from device independent pixels to real screen pixels, this ratio should be used whenever passing values into opengl calls since opengl doesn't work with device independent pixels. (see here for more info: https://doc.qt.io/qt-5/highdpi.html)
None?
Run grSim on a high dpi device
Added high dpi screen support to OpenGL window.

Fix glviewport scaling on high dpi

---

.travis.yml
CMakeLists.txt

👋 again! Please let me know of any feedback you've got on this. I know @mahi97 had a branch to do this, and I actually did this once (a different way) on https://github.com/RoboJackets/grSim, but I decided to start fresh and try an approach with externalproject. 
I think this should be a pretty safe way of doing it and should make building much easier.
closes #25 
If we can't find vartypes installed in the system with `find_package`, then clone it, install it to a `vartypes_install` directory in the build directory, and link to that version. We do this through cmake's external project tool. Note that I've made changes to vartype's build system to allow it to be built statically. This should prevent us from breaking install rules (we wouldn't want to depend on a shared library only in the …

Build vartypes inline if find_package fails

---

src/proto/grSim_Commands.proto
src/proto/grSim_Packet.proto
src/proto/grSim_Replacement.proto
src/proto/messages_robocup_ssl_detection.proto
src/proto/messages_robocup_ssl_geometry.proto
src/proto/messages_robocup_ssl_refbox_log.proto
src/proto/messages_robocup_ssl_wrapper.proto
src/sslworld.cpp

This should be merged after #96 
closes #97 
Users of grSim can specify a manual ball position and velocity through the `grSim_BallReplacement` proto message. This message requires position and velocity to be set in order to work. This PR makes those fields optional and reuses position or velocity values if they are not set in the proto, allowing users to only modify ball velocity if desired.
Could've added a whole new message, but this is nice and maintains compatibility.
None, users of the proto shouldn't be affected.
Manually modify client to send another packet with a replacement command that moves the ball, for example:
```cpp
grSim_Packet r_pkt;
r_pkt.mutable_replacement()->mutable_ball()->set_vx(-0.5);
r_pkt.mutable_replacement()->mutable_ball()->set_vy(-0.5); …
```

Make ball replacement fields optional

---

src/mainwindow.cpp

When setting Geometry > Game > Robots Count to 0, GrSim segfaults.
I threw GrSim in a debugger, and there is a bug in src/mainwindow.cpp. When there are no robots in the field, R is set to -1. This gives a segmentation fault. Putting that part of the code in an if-statement seems to fix it. I have not seen any other side effects of this change.

Fixed segmentation fault when settings 'Geometry>Game>Robots Count' to 0

---

src/configwidget.cpp

grSim can be installed under system's directories but is only able to load configuration files from it's relative directory:  _../config_.
- For Linux user, when grSim is executes under the _/usr/_ directory it will look into the configuration folder that is currently installed on the system: _/usr/local/share/grSim/config/_
- delete old code (useless)
As an alternative, we could use an environment variable and read it, if defined. This could be more flexible but introduce external modifications.
If an user changes the default install directory then no configuration can be load as before.
```bash
mkdir build && cd build
cmake ..
sudo make install
touch ../config/TMP.ini
grSim     # TMP.ini is not present in the configuration file list
```
Please close grSim.
```bash
rm ~/.grsim.xml  # to …
```

load configuration from system install directory on Linux (from NAMeC)

---

INSTALL.md
README.md

Add `pkg-config` to dependency in INSTALL.md and README.md 
#105 improved FindODE, but it added `pkg-config` as dependency QUIETLY. 
```cmake
find_package(PkgConfig QUIET)
```
This line will works fine if `pkg-config` is installed.
But if not, cmake output only shows error `Could not find ODE` even the problem is about pkg-config.  
And nothing about `pkg-config` is written in docs (excluding old CHANGELOG.md).  
It confusing (see #109).
So we need to update documents listed above.  
(Optionally, I think replacing "QUIET" with "REQUIRED" will make `cmake` error easier to debug. Could I have your opinion @Tosainu?)
Update documents (additional dependency)

add pkg-config to dependency in documents

---

include/mainwindow.h
include/robotwidget.h
src/mainwindow.cpp
src/robotwidget.cpp

Closes #116
Size of ID selection combo box in "Current Robot" widget is defined when RobotWidget object is created, and not updated even robot count is updated.
So, we can select a robot does not exists on field.  This causes out-of-range access and segmentation fault.
More details are described in #116 
Most of changes happen to configuration widget (e.g. number of robots, division, field size and more) are connected to `MainWindow::restartSimulator()`.
Now, I implemented new function `MainWindow::changeRobotCount()`, `RobotWidget::changeRobotCount()` and `RobotWidget::changeCurrentTeam()`.  
Change of robot count will call this.
`MainWindow::changeRobotCount()` follows those step:
1. clamp new robot count to fit to 0 ~ maximum robot count  
Currently it is 12, but will be increased to …

Shrink current robot selector comboBox based on robot count

---

src/sslworld.cpp

Closes #115 
When increase robot count from configuration widget, increased robot are placed to (x, y) = (0, 0) as show in #115.
This is happen because  
1. `RobotFomation::setAll()` only copies new robot position 0 ~ `Robots_Count()`
2. `setAll()` is only called when RobotFomation object is created
3. initial formations are defined in `RobotFomation::RobotFomation()` as temporal variable, so cannot refer from outside
Simply change condition used in `RobotFomation::setAll()` : `cfg->RobotCount()` to `MAX_ROBOT_COUNT`
This is a solution for 1.
Solving 2 and 3 is another way, but it is little bit complex and there're many way to implement.  
For example, with minimum changes,
1. create static formation constant in `RobotFomation` class
2. in `MainWindow::restartSimulator()`, initialize …

fix initial positions for increased robots

---

include/glwidget.h
include/mainwindow.h
src/glwidget.cpp
src/mainwindow.cpp

grSim crashed (segmentation fault) when;
- clicking buttons at the upper right of the simulator view.
- typing the F2 key (or the 'Full screen' checkbox in the 'Simulator' menu) to enter the full-screen mode and then typing the F2 key again to return from the full-screen mode.
I think that closing or minimizing the simulator view is not useful to us. Also, it is not needed to use the `QMdiArea` to show a single widget. This PR removes `QMdiArea` from the main window and sets `glwidget` directly to the central widget.
Detaching the widget and passing it to another widget is slightly hard to implement due to the limitation of [Qt's object management system](https://doc.qt.io/qt-5/objecttrees.html). This PR introduces a simpler implementation. After this change, grSim;
1. saves the current …

Fixed segmentation faults

---

include/glwidget.h
src/glwidget.cpp

N/A
Changes are only affect for `glwidget.[hpp, cpp]`.
- Merge duplicate function `resetRobot()` and `resetCurrentRobot()`
rename `resetRobot()` to `resetCurrentRobot()`, and delete old `resetCurrentRobot()`
- Simplify `switchRobotOnOff()`
Deleting `resetRobot()` and using `resetCurrentRobot()` is another way.
but `resetCurrentRobot()` has no check if `current robot` is valid and it may cause segfault
N/A, I think.
They're tiny changes only affect for internally so nothing changed for user.
At least both  `reset robot` and `Turn On/Off robot` action works, as usual, as expected.
N/A

Minor fixes

---

include/glwidget.h
include/graphics.h
src/glwidget.cpp
src/graphics.cpp

little bit related to #27 .
Those statements flags are treated as `int`.
adding enum to describe how those statements works makes easier to read code, and also we can write documentation easier.
N/A

Add enums for statements (camera mode, camera motion mode, 3D cursor mode)

---

INSTALL.md
README.md
resources/grsim.desktop

Fixes #126 
I have created a new package of grSim on the AUR, as quoted [here](https://github.com/RoboCup-SSL/grSim/issues/126). It seems to be working fine, so I have updated the INSTALL instructions file. I have changed a little the structure of  the part 'Linux/Unix installation' and have also added the install instruction on the end, please see if you agree with the changes that were made.
I have also updated the Desktop entry file.
Install instructions for Arch Linux systems; desktop entry file updated

Install instructions for arch linux and desktop shortcup updated

---

include/sslworld.h
src/sslworld.cpp

This implements the feature request https://github.com/RoboCup-SSL/grSim/issues/129
It adds the camera calibration to the ssl geometry data.
Add the camera calibration. Some values are dummy values as there is proper camera model behind the scenes.
The meaning of the variable "sendGeometryEvery" is slightly changes as now there will be sent 4 geometry packets in the frame indicated by sendGeometryEvery (one for each camera).
I cannot see any
I cannot see any
To verify that the generated positions are correct I visualized the position of the camera the ball is currently in in our framework after receiving the data. The positions were always in the center of the correct quadrant.
Add camera calibration to ssl geometry

Add camera calibration to ssl geometry

---

src/configwidget.cpp

closes #134
Updates the default values as described in #134.
-
-
Measure the velocity of objects using position and time difference.
Set fps and simulation step size to reasonable values

Set fps and simulation step size to reasonable values

---

src/sslworld.cpp

closes #70
The simulator publishes one frame per camera after each simulation step (~60fps).
Right now, a delay is added for each camera. cam0 -> 0ms, cam1 -> 1ms, cam2 -> 2ms, cam3 -> 3ms.
With the current implementation, the package for cam0 is send immediately, the other three are send with the next simulation step, so with 60fps about 16ms later.
This implementation seems unreasonable to me and I thus consider it a bug.
-
-
See #70 for a possible verification.
Remove delay for cams 1-3 when publishing packets

Remove delay for cams 1-3 when publishing packets

---

include/configwidget.h
src/configwidget.cpp
src/sslworld.cpp

[131](https://github.com/RoboCup-SSL/grSim/issues/131)
In ssl-vision, balls are always projected onto the field (see bugreport).
While ssl-vision already corrects these positions for the height of the ball itself, this correct is no longer correct as soon as the ball is being chipped.
In order to emulate ssl-visions behavior and make grSim closer to realitiy, we need to trace a ray from the camera to the ball.
The location where this ray would hit the field (corrected by the radius of the ball itself) will be reported by ssl-vision.
This distortion fails as soon as the ball is almost the same height as the camera itself. While the correct approach would be to not show the ball in these cases, I decided on simply bounding the height of the ball (subtracted its already corrected radius) by …

sslworld: project airbone balls

---

include/sslworld.h
src/sslworld.cpp

https://github.com/RoboCup-SSL/grSim/issues/124
Added concept of simulation time.
- Simulator now keeps track of simulated time.
- SSL packages now report simulated time instead of wall time.
Alternative was to report wall time instead of simulation time which makes simulation speed dependent of cpu performance and load.
None expected
Build grSim after changes.
Compared desired vs measured robot speed from 3rd party software under different fps.
SSL packages now reports the simulation time which allows for correct readings of simulated speeds.
Otherwise, the speed measured would depend on grSim's fps which would differ from the speed command sent to the robots.

Issue 124 - Added concept of simulation time.

---

.travis.yml
README.md

I have migrated all RoboCup-SSL repositories to travis-ci.com now.
This PR updates the URLs.
Additionally, I have changed the Linux distributions for which grSim is built. Ubuntu Trusty (14.04) is out of support since 2019 and Xenial (16.04) will be out of support in April. They hinder usage of more update-to-date APIs.

Migrate to travis-ci.com

---

src/sslworld.cpp

The ball is currently sliding very slowly over the field
sometimes, as no torque or force is added when the
velocity is <=0.01m/s.
This commit sets the velocity and angular velocity to 0
when the ball velocity is <=0.01m/s

Always let the ball come to a stop

---

.dockerignore
Dockerfile
INSTALL.md
docker-entry.sh
src/main.cpp
src/mainwindow.cpp
src/sslworld.cpp

This PR adds a Dockerfile that builds and bundles grSim.
It also contains some necessary tweak to make the container run without requiring a display. The available headless mode was not sufficient, as QT still tried to create a window.
I have not yet tested running it with the UI.
The image is already available on Docker Hub: https://hub.docker.com/r/robocupssl/grsim

Add dockerfile and make grSim run without a display

---

include/configwidget.h
include/physics/pobject.h
src/configwidget.cpp
src/graphics.cpp
src/mainwindow.cpp
src/physics/pobject.cpp
src/sslworld.cpp

Now the robots of yellow and blue team can have different "uniform" colors changing the values of `ROBOT_BLUE_CHASSIS_COLOR` and `ROBOT_YELLOW_CHASSIS_COLOR`.
The color will affect on the texture of the robot.
I still pretend to create a more convenience  way to change it the colors, maybe creating an option on the configurations space would be good.
* I am still not sure if I converted the QColor to the color format used on the software correctly [here](https://github.com/RoboCup-SSL/grSim/compare/master...Bollos00:master#diff-b2533f71bc10e2b3aeef4d49943cf283623d354f5a6690b3dc7c89bb3bcf64baR56);
* I do not know if the chances affect the performance of the software;
* It is not simple to change the equips uniform (carcase color);
* The textures of the robots are changed as well.
Changing …

Shortcut to exit grSim and different robot carcase color for each team

---

include/configwidget.h
src/configwidget.cpp
src/sslworld.cpp

In ssl-vision, I recently introduced ball parameters in the geometry message.
They are required by the autoRefs to correctly configure their ball models and may be useful for other teams as well.
It avoids explicit configuration and/or detection of the vision source, so the autoRefs can correctly run with any simulator, without additional configuration.
This PR just adds the parameters to the config tree and publishes them in the geometry message.
It might be possible to calculate the parameters based on the physics settings, but that was out of scope for me and could be done in a separate PR.

Write ball model parameters to new messages in geometry

---

.github/workflows/build.yaml
CMakeLists.txt
INSTALL.md
src/main.cpp

[Issue 145](https://github.com/RoboCup-SSL/grSim/issues/140)
Project modified so that it will compile in windows and so that it can be build using github actions.
4 changes added:
- Modified GitHub build action so that windows x64 is also tested on push.
- Defined Protobuf_IMPORT_DIRS in CMakeLists.txt (otherwise vc compiler doesn't find google.protobuf.any.proto)
- Included signals.h in main.cpp (otherwise windows compiler cannot find symbols 'signal' and 'SIGINT'
- Simplified windows installation instructions in INSTALL.md (changes reflect github's build workflow)
None considered
None foreseen
Code was compiled in windows on a personal laptop and through Github actions.
Code successfully compiled for all systems on GitHub.
N/A

Windows GitHub actions

---

src/configwidget.cpp

I first want to apology for not noticing this issue in the other pull request (when I added this feature). I will surely be more careful for now on.
I noticed that every time I opened grSim, a new option (Robot Color <color>) was created. (Not opened an issue).
That happened because those options were created after the Vartypes read the options from `~/.grsim.xml`. Changing the location of that line fixed the problem.
I also putted it on a different location that I found more appropriate. (Geometry > Game)
Nothing to increment.
Nothing to increment.
Installing, opening, closing the application several times.
Correction of multiple option Robot Color Yellow/Blue.

Correction of multiple option Robot Color Yellow/Blue

---

src/sslworld.cpp

#153 
With this change, teams are now judged by `grSim_commannds::isteamyellow` instead of `grSim_RobotReplacement::yellowteam` when RobotReplacement. So I changed to using `grSim_RobotReplacement::yellowteam`.
- If we set `grSim_commannds::isteamyellow`, we can do `RobotReplacement` correctly.
- This may be resolved with the migrate to the new standard protocol.
Systems that support the current version will not be able to RobotReplacement correctly.
I confirmed that the **yellow** `id` robot was repositioned with this code in our system.
```c++
ssl_protos::grsim::Packet packet{};
auto r = packet.mutable_replacement()->add_robots();
r->set_id(id);
r->set_x(x);
r->set_y(y);
r->set_dir(dir);
r->set_yellowteam(true);
connection_->send(packet.SerializeAsString());
```
N/A

Use `grSim_RobotReplacement::yellowteam` to determine the team

---

.gitignore
config/Parsian.ini
config/ParsianNew.ini
config/RoboIME2012.ini
include/configwidget.h
include/robot.h
include/sslworld.h
src/configwidget.cpp
src/mainwindow.cpp
src/proto/ssl_simulation_config.proto
src/robot.cpp
src/sslworld.cpp

This PR adds support for receiving the robotSpecs from the new protocol.
It overwrites existing robot configs and adds some new ones for limiting robot speed and kick speed.

Implement robotSpec handling of new protocol

---

src/mainwindow.cpp

I've found a small bug in #158. The `restartRequired` flag was not reset after consumption.

Reset flag for restarting simulation after consumption

---

src/robot.cpp

#160 
Handle the case when acceleration is higher than the limit and sent speed is zero by using the robot current speed as proposed @g3force 
I tried setting the limits directly to the wheel sent speeds, but this solution is simpler and requires less conversions
I've tested sending a robot speed for a fixed number of steps, then set the speed to zero. This test was done for different robot angles.
Not applicable

fix division by zero bug on robot spec handling

---

.github/workflows/build.yaml

CI to check build on windows fails with error below (see full log at https://github.com/RoboCup-SSL/grSim/actions/runs/3413239297/jobs/5679721865
<details>
<summary>Error found in build log for latest commit </summary>
````sh
Running 'vcpkg remove --outdated --recurse ' in directory 'c:\vcpkg' ...
There are no outdated packages.
Using triplet 'x64-windows'.
Set the environment variable 'RUNVCPKG_VCPKG_TRIPLET' to value: x64-windows
Set the output variable 'RUNVCPKG_VCPKG_TRIPLET_OUT' to value: x64-windows
Running 'vcpkg install --recurse qt5 ode protobuf --triplet x64-windows --clean-after-build' in directory 'c:\vcpkg' ...
Computing installation plan...
The following packages will be built and installed:
* brotli[core]:x64-windows -> 1.0.9
* bzip2[core]:x64-windows -> 1.0.8#1
* …
```

Fix CI `build-windows` : Update vcpkg to `2022.10.19` release

---

src/sslworld.cpp

This PR fixes #185 
When executing the `present=false` process, all robots are placed in different locations.

Set different positions when turning off robots with the robocup ssl protocol to avoid collisions between robots.

---

.github/workflows/build.yaml
CMakeLists.txt
CMakePresets.json
INSTALL.md
Makefile
clients/qt/CMakeLists.txt
cmake/modules/BuildODE.cmake
cmake/modules/BuildProtobuf.cmake
cmake/modules/EnvHelper.cmake
cmake/modules/FindOrBuildProtobuf.cmake
vcpkg.json

Builds Protobuf from source if the version is too new.
I'm not sure which protobuf version was the first to break, but if someone notices an incompatibility in the future they  can just adjust the maximum allowed version.
For ODE I didn't find a way to automatically detect incompatibility, because it doesn't seem to be completely dependent on the version number, but could also depend on build configurations of the package, like enabling double precision or not.
e.g. if double  precision is not enabled grSim crashes instantly, but with a different error than when using the Manjaro ode package.
So it ended up as an optional flag to enable building ODE from source.
Personally I'd make building ODE from source the default, but that seems more invasive than keeping the current behavior as …

Add Protobuf and ODE as ExternalProjects to cmake to fix platform compatibility issues
